### ISSUE TITLE
python cli TypeError

### ISSUE THREAD

**Issue by xuchen** [atlassistant/chatl#7]
when running the python CLI, I had:

TypeError: dumps() missing 1 required positional argument: 'obj'

Turns out you forgot to add `data` to:

    print(json.dumps(indent=2 if args.pretty else None))

https://github.com/atlassistant/chatl/blob/master/python/pychatl/cli.py#L43

This is an easy fix and I'm just too lazy to open a PR. 

Overall great work!

**Comment by YuukanOO** [comment]
Thanks for reporting! My mistake 😁

The 2.0.2 python version is now available: https://pypi.org/project/pychatl/2.0.2/
